### PR TITLE
Convert sample app to have zero dependencies

### PR DESCRIPTION
**Pull request by dgodd**
To better test ability for apps to be pushed to CF rather than test if bundler works. I propose changing the sample app to push to not have any dependencies.

### CODE REVIEW

**Comment by sclevine** [comment]
@SocalNick This fixes the occasional bundler flake. The root cause was addressed in ruby-core 5 days ago: https://github.com/bundler/bundler/issues/5886

**Comment by SocalNick** [comment]
@sclevine thanks! Looks like we'll need to wait for ruby 2.4.2

**Comment by dgodd** [comment]
@SocalNick I think using this PR would fix your problem today. This PR means that there are no dependencies for bundler to install. Given your test is around `cf push` and not bundler (or even ruby) making the switch seem to me, to be a reasonable trade-off.

**Comment by SocalNick** [comment]
Oh wow, you even removed Roda now. I'll bring this up at standup, thanks!

**Comment by SocalNick** [comment]
@dgodd we aren't feeling the pain around this any longer. We are ok waiting for ruby upgrade.

**Pull request closed without merging**
